language: python

python:
  - "3.6.3"

sudo: required

services:
  - docker

install:
  - pip install flask

script:
  - python test.py

after_success:
  - sh .travis/deploy_dockerhub.sh

deploy:
  provider: heroku
  api-key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME 
